from setuptools import setup

setup(name='intermediate-gradients',
      version='0.1.0',
      description='',
      author='Kieran Heese',
      author_email='kh8fb@virginia.edu',
      url='https://github.com/kh8fb/intermediate-gradients',
      packages=['intermediate_gradients'],
      install_requires=[
          "captum",
          "certifi",
          "chardet",
          "click",
          "cycler",
          "filelock",
          "future",
          "idna",
          "joblib",
          "kiwisolver",
          "matplotlib",
          "numpy",
          "packaging",
          "pyparsing",
          "python-dateutil",
          "regex",
          "requests",
          "sacremoses",
          "sentencepiece",
          "six",
          "tokenizers",
          "torch",
          "tqdm",
          "transformers",
          "urllib3",
      ]
     )
